
name: speechtotext
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.1.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^5.4.0
  cupertino_icons: ^1.0.8
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  timezone: ^0.9.4
  flutter_local_notifications: ^18.0.1 # Added for notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_signlogo.png
flutter_launcher_icons:
  image_path: assets/images/appicon.png
  android: true
  ios: true