// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkjbNf1bBHs6qexE0u3te5RjhRBLibi0',
    appId: '1:1070127954984:web:5e86751146bf68985d491d',
    messagingSenderId: '1070127954984',
    projectId: 'taskmanagement-64db7',
    authDomain: 'taskmanagement-64db7.firebaseapp.com',
    storageBucket: 'taskmanagement-64db7.firebasestorage.app',
    measurementId: 'G-MDY3TNS5ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGdNO-D-VmQYrrU2ktbrd_aS9ml3EzO0',
    appId: '1:1070127954984:android:bd207d7f14f6a9755d491d',
    messagingSenderId: '1070127954984',
    projectId: 'taskmanagement-64db7',
    storageBucket: 'taskmanagement-64db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2aUORq3GlWpBuz-GfiIuXKK2AQKgQ4ms',
    appId: '1:1070127954984:ios:57acfadcb3d04f445d491d',
    messagingSenderId: '1070127954984',
    projectId: 'taskmanagement-64db7',
    storageBucket: 'taskmanagement-64db7.firebasestorage.app',
    iosClientId: '1070127954984-rb8kaivmchi6s01fcg87vdjun49944qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechtotext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2aUORq3GlWpBuz-GfiIuXKK2AQKgQ4ms',
    appId: '1:1070127954984:ios:57acfadcb3d04f445d491d',
    messagingSenderId: '1070127954984',
    projectId: 'taskmanagement-64db7',
    storageBucket: 'taskmanagement-64db7.firebasestorage.app',
    iosClientId: '1070127954984-rb8kaivmchi6s01fcg87vdjun49944qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechtotext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYkjbNf1bBHs6qexE0u3te5RjhRBLibi0',
    appId: '1:1070127954984:web:aa67c47d363d3f035d491d',
    messagingSenderId: '1070127954984',
    projectId: 'taskmanagement-64db7',
    authDomain: 'taskmanagement-64db7.firebaseapp.com',
    storageBucket: 'taskmanagement-64db7.firebasestorage.app',
    measurementId: 'G-EM8FY3CLE7',
  );
}
